name: rebase branch wf
on:
  push:
    branches:
    - GHA-demo

jobs:
  move-branch:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2


      - name: git list
        run: git branch -a

      - run: echo ${{ github.ref }}

      - name: git checkout
        run: git checkout test3

      - name: git rebase
        run: git rebase GHA-demo

      - name: git checkout back
        run: git checkout ${{ github.ref }}